export interface ProfileTheme {
  id: string;
  name: string;
  nameAr: string;
  category: "gradient" | "solid" | "glassmorphism" | "neon" | "minimal" | "artistic" | "seasonal" | "premium";
  background: string;
  card: string;
  text: string;
  accent: string;
  buttonRadius: string;
  buttonStyle?: string;
  fontFamily?: string;
  animation?: string;
  isPremium?: boolean;
  preview?: string;
}

export const PROFILE_THEMES: ProfileTheme[] = [
  // ==================== GRADIENT THEMES ====================
  {
    id: "default",
    name: "Default",
    nameAr: "الافتراضي",
    category: "solid",
    background: "bg-background",
    card: "bg-card hover:bg-card/80",
    text: "text-foreground",
    accent: "text-primary",
    buttonRadius: "rounded-2xl",
    buttonStyle: "border border-border shadow-sm hover:shadow-md transition-all duration-300",
  },
  {
    id: "ocean",
    name: "Ocean Breeze",
    nameAr: "نسيم المحيط",
    category: "gradient",
    background: "bg-gradient-to-br from-blue-500 via-cyan-400 to-teal-400",
    card: "bg-white/20 backdrop-blur-md border-white/30 hover:bg-white/30",
    text: "text-white",
    accent: "text-blue-100",
    buttonRadius: "rounded-full",
    buttonStyle: "shadow-lg hover:shadow-xl hover:scale-[1.02] transition-all duration-300",
    animation: "animate-gradient-slow",
  },
  {
    id: "sunset",
    name: "Sunset Glow",
    nameAr: "توهج الغروب",
    category: "gradient",
    background: "bg-gradient-to-br from-orange-500 via-pink-500 to-purple-600",
    card: "bg-white/10 backdrop-blur-lg border-white/20 hover:bg-white/20",
    text: "text-white",
    accent: "text-orange-100",
    buttonRadius: "rounded-xl",
    buttonStyle: "shadow-lg hover:shadow-2xl hover:scale-[1.02] transition-all duration-300",
    animation: "animate-gradient-slow",
  },
  {
    id: "aurora",
    name: "Aurora Borealis",
    nameAr: "الشفق القطبي",
    category: "gradient",
    background: "bg-gradient-to-br from-green-400 via-blue-500 to-purple-600",
    card: "bg-white/15 backdrop-blur-xl border-white/25 hover:bg-white/25",
    text: "text-white",
    accent: "text-green-200",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-xl hover:shadow-2xl hover:scale-[1.03] transition-all duration-300",
    animation: "animate-aurora",
  },
  {
    id: "cosmic",
    name: "Cosmic Dream",
    nameAr: "حلم كوني",
    category: "gradient",
    background: "bg-gradient-to-br from-indigo-900 via-purple-900 to-pink-800",
    card: "bg-white/10 backdrop-blur-lg border-purple-500/30 hover:border-purple-400/50",
    text: "text-white",
    accent: "text-purple-300",
    buttonRadius: "rounded-3xl",
    buttonStyle: "shadow-lg shadow-purple-500/20 hover:shadow-purple-500/40 transition-all duration-300",
  },
  {
    id: "tropical",
    name: "Tropical Paradise",
    nameAr: "جنة استوائية",
    category: "gradient",
    background: "bg-gradient-to-br from-yellow-400 via-orange-500 to-pink-500",
    card: "bg-white/20 backdrop-blur-md border-white/30 hover:bg-white/30",
    text: "text-white",
    accent: "text-yellow-100",
    buttonRadius: "rounded-full",
    buttonStyle: "shadow-lg hover:shadow-xl transition-all duration-300",
  },
  {
    id: "lavender",
    name: "Lavender Fields",
    nameAr: "حقول اللافندر",
    category: "gradient",
    background: "bg-gradient-to-br from-purple-400 via-pink-300 to-indigo-400",
    card: "bg-white/25 backdrop-blur-md border-white/40 hover:bg-white/35",
    text: "text-white",
    accent: "text-purple-100",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-md hover:shadow-lg transition-all duration-300",
  },
  {
    id: "fire",
    name: "Fire Storm",
    nameAr: "عاصفة نارية",
    category: "gradient",
    background: "bg-gradient-to-br from-red-600 via-orange-500 to-yellow-500",
    card: "bg-black/20 backdrop-blur-lg border-orange-500/30 hover:border-orange-400/50",
    text: "text-white",
    accent: "text-orange-200",
    buttonRadius: "rounded-xl",
    buttonStyle: "shadow-lg shadow-orange-500/30 hover:shadow-orange-500/50 transition-all duration-300",
    animation: "animate-pulse-slow",
  },
  {
    id: "ice",
    name: "Ice Crystal",
    nameAr: "كريستال جليدي",
    category: "gradient",
    background: "bg-gradient-to-br from-cyan-200 via-blue-300 to-indigo-400",
    card: "bg-white/40 backdrop-blur-xl border-white/60 hover:bg-white/50",
    text: "text-slate-800",
    accent: "text-blue-600",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-lg hover:shadow-xl transition-all duration-300",
  },

  // ==================== SOLID THEMES ====================
  {
    id: "midnight",
    name: "Midnight",
    nameAr: "منتصف الليل",
    category: "solid",
    background: "bg-slate-950",
    card: "bg-slate-900 border-slate-800 hover:bg-slate-800/80",
    text: "text-slate-100",
    accent: "text-blue-400",
    buttonRadius: "rounded-lg",
    buttonStyle: "border border-slate-700 hover:border-slate-600 transition-all duration-300",
  },
  {
    id: "forest",
    name: "Forest",
    nameAr: "الغابة",
    category: "solid",
    background: "bg-gradient-to-b from-emerald-900 to-green-950",
    card: "bg-emerald-800/40 border-emerald-700/50 hover:bg-emerald-800/60",
    text: "text-emerald-50",
    accent: "text-emerald-300",
    buttonRadius: "rounded-3xl",
    buttonStyle: "shadow-md hover:shadow-lg transition-all duration-300",
  },
  {
    id: "charcoal",
    name: "Charcoal",
    nameAr: "الفحمي",
    category: "solid",
    background: "bg-neutral-900",
    card: "bg-neutral-800 border-neutral-700 hover:bg-neutral-700/80",
    text: "text-neutral-100",
    accent: "text-neutral-400",
    buttonRadius: "rounded-xl",
    buttonStyle: "border border-neutral-600 hover:border-neutral-500 transition-all duration-300",
  },
  {
    id: "navy",
    name: "Navy Blue",
    nameAr: "الأزرق الداكن",
    category: "solid",
    background: "bg-blue-950",
    card: "bg-blue-900/60 border-blue-800/50 hover:bg-blue-900/80",
    text: "text-blue-50",
    accent: "text-blue-300",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-md hover:shadow-lg transition-all duration-300",
  },
  {
    id: "wine",
    name: "Wine Red",
    nameAr: "النبيذي",
    category: "solid",
    background: "bg-rose-950",
    card: "bg-rose-900/50 border-rose-800/40 hover:bg-rose-900/70",
    text: "text-rose-50",
    accent: "text-rose-300",
    buttonRadius: "rounded-xl",
    buttonStyle: "shadow-md hover:shadow-lg transition-all duration-300",
  },

  // ==================== MINIMAL THEMES ====================
  {
    id: "minimal",
    name: "Minimal White",
    nameAr: "أبيض بسيط",
    category: "minimal",
    background: "bg-zinc-50",
    card: "bg-white border-zinc-200 shadow-sm hover:shadow-md",
    text: "text-zinc-900",
    accent: "text-zinc-500",
    buttonRadius: "rounded-none",
    buttonStyle: "border-2 border-zinc-900 hover:bg-zinc-900 hover:text-white transition-all duration-300",
  },
  {
    id: "paper",
    name: "Paper",
    nameAr: "ورقي",
    category: "minimal",
    background: "bg-amber-50",
    card: "bg-white border-amber-200 shadow-sm hover:shadow-md",
    text: "text-amber-900",
    accent: "text-amber-600",
    buttonRadius: "rounded-lg",
    buttonStyle: "border border-amber-300 hover:bg-amber-100 transition-all duration-300",
  },
  {
    id: "clean",
    name: "Clean Slate",
    nameAr: "نظيف",
    category: "minimal",
    background: "bg-gray-100",
    card: "bg-white border-gray-200 shadow-sm hover:shadow-lg",
    text: "text-gray-800",
    accent: "text-gray-500",
    buttonRadius: "rounded-xl",
    buttonStyle: "border border-gray-300 hover:border-gray-400 transition-all duration-300",
  },
  {
    id: "mono",
    name: "Monochrome",
    nameAr: "أحادي اللون",
    category: "minimal",
    background: "bg-white",
    card: "bg-black text-white hover:bg-gray-900",
    text: "text-black",
    accent: "text-gray-600",
    buttonRadius: "rounded-full",
    buttonStyle: "shadow-lg hover:shadow-xl transition-all duration-300",
  },

  // ==================== GLASSMORPHISM THEMES ====================
  {
    id: "glass-dark",
    name: "Dark Glass",
    nameAr: "زجاج داكن",
    category: "glassmorphism",
    background: "bg-gradient-to-br from-gray-900 via-slate-900 to-zinc-900",
    card: "bg-white/10 backdrop-blur-xl border-white/20 hover:bg-white/15",
    text: "text-white",
    accent: "text-gray-300",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-xl hover:shadow-2xl transition-all duration-300",
  },
  {
    id: "glass-light",
    name: "Light Glass",
    nameAr: "زجاج فاتح",
    category: "glassmorphism",
    background: "bg-gradient-to-br from-blue-100 via-purple-100 to-pink-100",
    card: "bg-white/60 backdrop-blur-xl border-white/80 hover:bg-white/70",
    text: "text-gray-800",
    accent: "text-purple-600",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-lg hover:shadow-xl transition-all duration-300",
  },
  {
    id: "frosted",
    name: "Frosted",
    nameAr: "ضبابي",
    category: "glassmorphism",
    background: "bg-gradient-to-br from-slate-200 via-gray-200 to-zinc-300",
    card: "bg-white/70 backdrop-blur-2xl border-white/90 hover:bg-white/80",
    text: "text-slate-800",
    accent: "text-slate-500",
    buttonRadius: "rounded-3xl",
    buttonStyle: "shadow-md hover:shadow-lg transition-all duration-300",
  },
  {
    id: "crystal",
    name: "Crystal Clear",
    nameAr: "كريستال شفاف",
    category: "glassmorphism",
    background: "bg-gradient-to-br from-cyan-100 via-blue-100 to-indigo-200",
    card: "bg-white/50 backdrop-blur-2xl border-white/70 hover:bg-white/60",
    text: "text-indigo-900",
    accent: "text-cyan-600",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-lg shadow-blue-200/50 hover:shadow-xl transition-all duration-300",
  },

  // ==================== NEON THEMES ====================
  {
    id: "neon-pink",
    name: "Neon Pink",
    nameAr: "نيون وردي",
    category: "neon",
    background: "bg-black",
    card: "bg-black border-2 border-pink-500 hover:border-pink-400 hover:shadow-pink-500/50 hover:shadow-lg",
    text: "text-white",
    accent: "text-pink-500",
    buttonRadius: "rounded-lg",
    buttonStyle: "shadow-[0_0_15px_rgba(236,72,153,0.5)] hover:shadow-[0_0_25px_rgba(236,72,153,0.7)] transition-all duration-300",
    animation: "animate-neon-glow",
  },
  {
    id: "neon-blue",
    name: "Neon Blue",
    nameAr: "نيون أزرق",
    category: "neon",
    background: "bg-slate-950",
    card: "bg-slate-950 border-2 border-cyan-400 hover:border-cyan-300 hover:shadow-cyan-400/50 hover:shadow-lg",
    text: "text-white",
    accent: "text-cyan-400",
    buttonRadius: "rounded-lg",
    buttonStyle: "shadow-[0_0_15px_rgba(34,211,238,0.5)] hover:shadow-[0_0_25px_rgba(34,211,238,0.7)] transition-all duration-300",
    animation: "animate-neon-glow",
  },
  {
    id: "neon-green",
    name: "Neon Green",
    nameAr: "نيون أخضر",
    category: "neon",
    background: "bg-gray-950",
    card: "bg-gray-950 border-2 border-green-400 hover:border-green-300 hover:shadow-green-400/50 hover:shadow-lg",
    text: "text-white",
    accent: "text-green-400",
    buttonRadius: "rounded-lg",
    buttonStyle: "shadow-[0_0_15px_rgba(74,222,128,0.5)] hover:shadow-[0_0_25px_rgba(74,222,128,0.7)] transition-all duration-300",
    animation: "animate-neon-glow",
  },
  {
    id: "neon-purple",
    name: "Neon Purple",
    nameAr: "نيون بنفسجي",
    category: "neon",
    background: "bg-zinc-950",
    card: "bg-zinc-950 border-2 border-violet-500 hover:border-violet-400 hover:shadow-violet-500/50 hover:shadow-lg",
    text: "text-white",
    accent: "text-violet-400",
    buttonRadius: "rounded-lg",
    buttonStyle: "shadow-[0_0_15px_rgba(139,92,246,0.5)] hover:shadow-[0_0_25px_rgba(139,92,246,0.7)] transition-all duration-300",
    animation: "animate-neon-glow",
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    nameAr: "سايبربانك",
    category: "neon",
    background: "bg-gradient-to-br from-purple-950 via-black to-cyan-950",
    card: "bg-black/80 border border-cyan-500/50 hover:border-pink-500/50 hover:shadow-lg",
    text: "text-cyan-100",
    accent: "text-pink-400",
    buttonRadius: "rounded-none",
    buttonStyle: "border-l-4 border-l-cyan-400 shadow-lg hover:border-l-pink-400 transition-all duration-300",
  },

  // ==================== ARTISTIC THEMES ====================
  {
    id: "watercolor",
    name: "Watercolor",
    nameAr: "ألوان مائية",
    category: "artistic",
    background: "bg-gradient-to-br from-pink-200 via-purple-200 to-blue-200",
    card: "bg-white/60 backdrop-blur-sm border-white/80 hover:bg-white/70",
    text: "text-purple-900",
    accent: "text-pink-600",
    buttonRadius: "rounded-full",
    buttonStyle: "shadow-md hover:shadow-lg transition-all duration-300",
  },
  {
    id: "vintage",
    name: "Vintage",
    nameAr: "كلاسيكي",
    category: "artistic",
    background: "bg-amber-100",
    card: "bg-amber-50 border-2 border-amber-300 hover:border-amber-400",
    text: "text-amber-900",
    accent: "text-amber-700",
    buttonRadius: "rounded-sm",
    buttonStyle: "border-2 border-amber-700 hover:bg-amber-700 hover:text-amber-50 transition-all duration-300",
    fontFamily: "font-serif",
  },
  {
    id: "retro",
    name: "Retro Wave",
    nameAr: "ريترو",
    category: "artistic",
    background: "bg-gradient-to-b from-purple-800 via-pink-600 to-orange-500",
    card: "bg-black/30 backdrop-blur-md border-yellow-400/50 hover:border-yellow-300",
    text: "text-yellow-100",
    accent: "text-yellow-300",
    buttonRadius: "rounded-none",
    buttonStyle: "border-2 border-yellow-400 shadow-lg hover:shadow-yellow-400/30 transition-all duration-300",
  },
  {
    id: "pastel",
    name: "Pastel Dream",
    nameAr: "ألوان باستيل",
    category: "artistic",
    background: "bg-gradient-to-br from-pink-100 via-yellow-100 to-cyan-100",
    card: "bg-white/80 backdrop-blur-sm border-pink-200 hover:border-pink-300",
    text: "text-gray-700",
    accent: "text-pink-500",
    buttonRadius: "rounded-3xl",
    buttonStyle: "shadow-sm hover:shadow-md transition-all duration-300",
  },
  {
    id: "marble",
    name: "Marble",
    nameAr: "رخامي",
    category: "artistic",
    background: "bg-gradient-to-br from-gray-100 via-white to-gray-200",
    card: "bg-white border border-gray-300 shadow-sm hover:shadow-md",
    text: "text-gray-800",
    accent: "text-gray-500",
    buttonRadius: "rounded-xl",
    buttonStyle: "border border-gray-400 hover:bg-gray-100 transition-all duration-300",
  },

  // ==================== SEASONAL THEMES ====================
  {
    id: "spring",
    name: "Spring Bloom",
    nameAr: "ربيع مزهر",
    category: "seasonal",
    background: "bg-gradient-to-br from-green-200 via-pink-200 to-yellow-200",
    card: "bg-white/70 backdrop-blur-sm border-green-300/50 hover:border-pink-300/50",
    text: "text-green-900",
    accent: "text-pink-600",
    buttonRadius: "rounded-full",
    buttonStyle: "shadow-md hover:shadow-lg transition-all duration-300",
  },
  {
    id: "summer",
    name: "Summer Vibes",
    nameAr: "صيف حيوي",
    category: "seasonal",
    background: "bg-gradient-to-br from-yellow-300 via-orange-400 to-red-400",
    card: "bg-white/25 backdrop-blur-md border-white/40 hover:bg-white/35",
    text: "text-white",
    accent: "text-yellow-100",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-lg hover:shadow-xl transition-all duration-300",
  },
  {
    id: "autumn",
    name: "Autumn Leaves",
    nameAr: "أوراق الخريف",
    category: "seasonal",
    background: "bg-gradient-to-br from-orange-700 via-red-700 to-amber-800",
    card: "bg-amber-900/40 backdrop-blur-md border-orange-600/40 hover:bg-amber-900/60",
    text: "text-amber-50",
    accent: "text-orange-300",
    buttonRadius: "rounded-xl",
    buttonStyle: "shadow-md hover:shadow-lg transition-all duration-300",
  },
  {
    id: "winter",
    name: "Winter Frost",
    nameAr: "صقيع الشتاء",
    category: "seasonal",
    background: "bg-gradient-to-br from-blue-200 via-white to-cyan-200",
    card: "bg-white/80 backdrop-blur-xl border-blue-200 hover:border-blue-300",
    text: "text-blue-900",
    accent: "text-cyan-600",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-lg shadow-blue-100 hover:shadow-xl transition-all duration-300",
  },

  // ==================== PREMIUM THEMES ====================
  {
    id: "gold",
    name: "Golden Luxury",
    nameAr: "ذهبي فاخر",
    category: "premium",
    isPremium: true,
    background: "bg-gradient-to-br from-yellow-600 via-amber-500 to-yellow-700",
    card: "bg-black/30 backdrop-blur-lg border-yellow-400/50 hover:border-yellow-300",
    text: "text-yellow-50",
    accent: "text-yellow-300",
    buttonRadius: "rounded-xl",
    buttonStyle: "shadow-lg shadow-yellow-500/30 hover:shadow-yellow-500/50 transition-all duration-300",
  },
  {
    id: "platinum",
    name: "Platinum Elite",
    nameAr: "بلاتيني",
    category: "premium",
    isPremium: true,
    background: "bg-gradient-to-br from-gray-300 via-gray-100 to-gray-400",
    card: "bg-white/90 backdrop-blur-xl border-gray-300 shadow-lg hover:shadow-xl",
    text: "text-gray-800",
    accent: "text-gray-500",
    buttonRadius: "rounded-2xl",
    buttonStyle: "border border-gray-400 shadow-md hover:shadow-lg transition-all duration-300",
  },
  {
    id: "diamond",
    name: "Diamond Shine",
    nameAr: "لمعان الماس",
    category: "premium",
    isPremium: true,
    background: "bg-gradient-to-br from-cyan-100 via-white to-blue-100",
    card: "bg-white/95 backdrop-blur-2xl border-cyan-200 shadow-xl hover:shadow-2xl",
    text: "text-cyan-900",
    accent: "text-cyan-500",
    buttonRadius: "rounded-3xl",
    buttonStyle: "shadow-lg shadow-cyan-200/50 hover:shadow-cyan-300/70 transition-all duration-300",
  },
  {
    id: "royal",
    name: "Royal Purple",
    nameAr: "بنفسجي ملكي",
    category: "premium",
    isPremium: true,
    background: "bg-gradient-to-br from-purple-900 via-indigo-900 to-violet-900",
    card: "bg-purple-800/40 backdrop-blur-lg border-purple-500/40 hover:border-purple-400/60",
    text: "text-purple-50",
    accent: "text-purple-300",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-lg shadow-purple-500/30 hover:shadow-purple-500/50 transition-all duration-300",
  },
  {
    id: "emerald",
    name: "Emerald Gem",
    nameAr: "زمرد",
    category: "premium",
    isPremium: true,
    background: "bg-gradient-to-br from-emerald-700 via-green-600 to-teal-700",
    card: "bg-emerald-900/40 backdrop-blur-lg border-emerald-400/40 hover:border-emerald-300/60",
    text: "text-emerald-50",
    accent: "text-emerald-300",
    buttonRadius: "rounded-xl",
    buttonStyle: "shadow-lg shadow-emerald-500/30 hover:shadow-emerald-500/50 transition-all duration-300",
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    nameAr: "ذهب وردي",
    category: "premium",
    isPremium: true,
    background: "bg-gradient-to-br from-rose-300 via-pink-200 to-orange-200",
    card: "bg-white/70 backdrop-blur-xl border-rose-300/50 hover:border-rose-400/70",
    text: "text-rose-900",
    accent: "text-rose-500",
    buttonRadius: "rounded-full",
    buttonStyle: "shadow-lg shadow-rose-200/50 hover:shadow-rose-300/70 transition-all duration-300",
  },
  {
    id: "obsidian",
    name: "Obsidian Black",
    nameAr: "أسود سبج",
    category: "premium",
    isPremium: true,
    background: "bg-black",
    card: "bg-zinc-900 border border-zinc-700 hover:border-zinc-600",
    text: "text-zinc-100",
    accent: "text-zinc-400",
    buttonRadius: "rounded-lg",
    buttonStyle: "border border-zinc-600 shadow-lg hover:shadow-xl transition-all duration-300",
  },
  {
    id: "holographic",
    name: "Holographic",
    nameAr: "هولوغرافي",
    category: "premium",
    isPremium: true,
    background: "bg-gradient-to-br from-pink-300 via-purple-300 to-cyan-300",
    card: "bg-white/40 backdrop-blur-2xl border-white/60 hover:bg-white/50",
    text: "text-purple-900",
    accent: "text-pink-600",
    buttonRadius: "rounded-2xl",
    buttonStyle: "shadow-xl hover:shadow-2xl transition-all duration-300",
    animation: "animate-holographic",
  },
];

// Helper function to get themes by category
export const getThemesByCategory = (category: ProfileTheme["category"]) => {
  return PROFILE_THEMES.filter((theme) => theme.category === category);
};

// Helper function to get free themes only
export const getFreeThemes = () => {
  return PROFILE_THEMES.filter((theme) => !theme.isPremium);
};

// Helper function to get premium themes only
export const getPremiumThemes = () => {
  return PROFILE_THEMES.filter((theme) => theme.isPremium);
};

// Theme categories for display
export const THEME_CATEGORIES = [
  { id: "gradient", name: "Gradient", nameAr: "متدرج", icon: "🌈" },
  { id: "solid", name: "Solid", nameAr: "صلب", icon: "🎨" },
  { id: "glassmorphism", name: "Glass", nameAr: "زجاجي", icon: "🪟" },
  { id: "neon", name: "Neon", nameAr: "نيون", icon: "💡" },
  { id: "minimal", name: "Minimal", nameAr: "بسيط", icon: "✨" },
  { id: "artistic", name: "Artistic", nameAr: "فني", icon: "🎭" },
  { id: "seasonal", name: "Seasonal", nameAr: "موسمي", icon: "🍂" },
  { id: "premium", name: "Premium", nameAr: "مميز", icon: "👑" },
] as const;
